MovieAppBundle\Entity\Genre:
    type: entity
    table: genre
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 85
            unique: true



