MovieAppBundle\Entity\User:
    type:  entity
    table: users
    id:
        id:
            type: integer
            generator:
                strategy: AUTO

    manyToMany:
            groups:
                targetEntity:   UserGroup
                inversedBy:     users
                joinTable:
                    name:       user_to_group
                    joinColumns:
                        user_id:
                            referencedColumnName: id
                    inverseJoinColumns:
                        group_id:
                            referencedColumnName: id