fos_user:
    db_driver:      orm
    firewall_name:  main
    user_class:     MovieAppBundle\Entity\User
    group:
        group_class: MovieAppBundle\Entity\UserGroup
imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
            resources: ['bootstrap_3_horizontal_layout.html.twig']

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: '%kernel.debug%'
    bundles:        [MovieAppBundle,FOSUserBundle]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

#TwitterBootstrapBundle
twitter_bootstrap:
    local_js: '@MovieAppBundle/Resources/public/js/bootstrap.min.js'
    local_fonts_dir: '@MovieAppBundle/Resources/public/fonts/'
    local_css: '@MovieAppBundle/Resources/public/css/bootstrap.min.css'
    local_theme: '@MovieAppBundle/Resources/public/css/bootstrap-theme.min.css'
    local_cdn: 'cdn.domain.com'
    version: 3.3.4
    html5: true
    async: false

vich_uploader:
    db_driver: orm # or mongodb or propel or phpcr

    mappings:
        movie_image:
            uri_prefix:         /images/movies
            upload_destination: %kernel.root_dir%/../web/images/movies
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true