genre:
    path:     /
    defaults: { _controller: "MovieAppBundle:Genre:index" }

genre_show:
    path:     /{id}/show
    defaults: { _controller: "MovieAppBundle:Genre:show" }

genre_new:
    path:     /new
    defaults: { _controller: "MovieAppBundle:Genre:new" }

genre_create:
    path:     /create
    defaults: { _controller: "MovieAppBundle:Genre:create" }
    methods:  POST

genre_edit:
    path:     /{id}/edit
    defaults: { _controller: "MovieAppBundle:Genre:edit" }

genre_update:
    path:     /{id}/update
    defaults: { _controller: "MovieAppBundle:Genre:update" }
    methods:  [POST, PUT]

genre_delete:
    path:     /{id}/delete
    defaults: { _controller: "MovieAppBundle:Genre:delete" }
    methods:  [POST, DELETE]
