movie_app_admin_tags:
    resource: "@MovieAppBundle/Resources/config/routing/tags.yml"
    prefix:   /admin/tags

movie_app_admin_genre:
    resource: "@MovieAppBundle/Resources/config/routing/genre.yml"
    prefix:   /admin/genre

movie_app_admin_category:
    resource: "@MovieAppBundle/Resources/config/routing/category.yml"
    prefix:   /admin/category

movie_app_admin_movies:
    resource: "@MovieAppBundle/Resources/config/routing/movie.yml"
    prefix:   /admin/movies

movie_app_homepage:
    path:     /
    defaults: { _controller: MovieAppBundle:Default:index }

movie_app_category:
    path:     /category/{id}
    defaults:  { _controller:  MovieAppBundle:Category:content }


movie_app_movie:
    path:     /movie/{id}
    defaults:  { _controller:  MovieAppBundle:Movie:moviedetails }
